In [1]:
import tensorflow as tf

In [2]:
x = tf.constant(4.0)
print(x)

tf.Tensor(4.0, shape=(), dtype=float32)


In [3]:
# Rank 0
x = tf.constant(4.0, shape=(1,1), dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [4]:
# Rank 1
y = tf.constant([2.0, 3.0, 4.0], shape=(3,1), dtype=tf.float32)
print(y)

tf.Tensor(
[[2.]
 [3.]
 [4.]], shape=(3, 1), dtype=float32)


In [5]:
# Rank 2
z = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.float32)
print(z)
#

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)


In [6]:
x = tf.ones((3,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [7]:
y = tf.zeros((2,2))
print(y)
#

tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)


In [8]:
z = tf.eye(3)
print(z)
#

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [9]:
x = tf.random.normal((3,3), mean=0.0, stddev=1.0)
print(x)

tf.Tensor(
[[ 0.0893593   0.3292425  -0.02295197]
 [-0.8021219   0.3274191   0.96200633]
 [-0.5889442   1.2094457  -0.6177576 ]], shape=(3, 3), dtype=float32)


In [10]:
y = tf.random.uniform((3,3), minval=0, maxval=1)
print(y)
#

tf.Tensor(
[[0.15430224 0.8941746  0.00231147]
 [0.2676847  0.5510737  0.10702586]
 [0.8656645  0.48738623 0.35395443]], shape=(3, 3), dtype=float32)


In [40]:
x = tf.range(10)
print(x)
#

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [41]:
x = tf.cast(x, dtype=tf.float32)
print(x)
#

tf.Tensor([0. 1. 2. 3. 4. 5. 6. 7. 8. 9.], shape=(10,), dtype=float32)


In [39]:
x = tf.constant([1,2,3])
y = tf.constant([4,5,6])

z = tf.add(x,y)
z = x + y
print(z)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [14]:
z = tf.subtract(x,y)
z = x - y
print(z)


tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)


In [15]:

z = tf.divide(x,y)
z = x / y
print(z)



tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)


In [16]:
z = tf.multiply(x,y)
z = x * y
print(z)

tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [17]:
z = tf.tensordot(x,y, axes=1)
print(z)

tf.Tensor(32, shape=(), dtype=int32)


In [18]:
z = x ** 3
print(z)

tf.Tensor([ 1  8 27], shape=(3,), dtype=int32)


In [19]:
x = tf.random.normal((2,3)) # 2,3
y = tf.random.normal((3,4)) # 3,4

z = tf.matmul(x,y)
z = x @ y
print(z)

tf.Tensor(
[[ 0.21862364 -0.8110344   0.37608746 -0.5276079 ]
 [-1.4536133  -1.2803459   2.141914    2.2567465 ]], shape=(2, 4), dtype=float32)


In [20]:
x = tf.constant([[1,2,3,4],[5,6,7,8]])
print(x[0])
print(x[:, 0]) # all rows, column 0
print(x[1, :]) # row 1, all columns
print(x[1,1]) # element at 1, 1

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([1 5], shape=(2,), dtype=int32)
tf.Tensor([5 6 7 8], shape=(4,), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


In [21]:
x = tf.random.normal((2,3))
print(x)

tf.Tensor(
[[ 0.35045204 -1.6430894   0.2858105 ]
 [-1.0202653   0.7467837  -0.986664  ]], shape=(2, 3), dtype=float32)


In [22]:
x = tf.reshape(x, (3,2))
print(x)

tf.Tensor(
[[ 0.35045204 -1.6430894 ]
 [ 0.2858105  -1.0202653 ]
 [ 0.7467837  -0.986664  ]], shape=(3, 2), dtype=float32)


In [23]:
x = tf.reshape(x, (-1,2))
print(x)

tf.Tensor(
[[ 0.35045204 -1.6430894 ]
 [ 0.2858105  -1.0202653 ]
 [ 0.7467837  -0.986664  ]], shape=(3, 2), dtype=float32)


In [24]:
x = tf.reshape(x, (6))
print(x)

tf.Tensor([ 0.35045204 -1.6430894   0.2858105  -1.0202653   0.7467837  -0.986664  ], shape=(6,), dtype=float32)


In [25]:
x = x.numpy()
print(type(x))

<class 'numpy.ndarray'>


In [26]:
x = tf.convert_to_tensor(x)
print(type(x))

<class 'tensorflow.python.framework.ops.EagerTensor'>


In [27]:
x = tf.constant("Patrick")
print(x)

tf.Tensor(b'Patrick', shape=(), dtype=string)


In [28]:
x = tf.constant(["Patrick", "Max", "Mary"])
print(x)

tf.Tensor([b'Patrick' b'Max' b'Mary'], shape=(3,), dtype=string)


In [29]:
b = tf.Variable([[1.0, 2.0, 3.0]])
print(b)
print(type(b))

<tf.Variable 'Variable:0' shape=(1, 3) dtype=float32, numpy=array([[1., 2., 3.]], dtype=float32)>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
